{{- if not .Values.mergeAllViews }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rawTraceView.generator.deploymentName }}
  labels:
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- toYaml .Values.rawTraceView.generator.deploymentSelectorMatchLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.rawTraceView.generator.podLabels | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.containerAdminPort }}"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: view-gen-service-config
          configMap:
            name: {{ .Values.viewGeneratorServiceConfig.name }}
        - name: log4j-config
          configMap:
            name: {{ .Values.logConfig.name }}
    {{- with .Values.nodeLabels }}
      nodeSelector:
      {{- toYaml . | nindent 8}}
    {{- end }}
      containers:
        - name: {{ .Values.rawTraceView.generator.deploymentName }}
          image: "{{ .Values.images.generator.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: admin-port
              containerPort: {{ .Values.containerAdminPort }}
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: "view-gen-raw-traces"
            - name: CLUSTER_NAME
              value: "staging"
            - name: BOOTSTRAP_CONFIG_URI
              value: "file:///app/resources/configs"
            - name: LOG4J_CONFIGURATION_FILE
              value: "/var/{{ .Values.rawTraceView.generator.deploymentName }}/log/log4j2.properties"
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.rawTraceView.generator.javaOpts | quote }}
          volumeMounts:
            - name: view-gen-service-config
              mountPath: /app/resources/configs/common/staging/application.conf
              subPath: application.conf
            - name: log4j-config
              mountPath: /var/{{ .Values.rawTraceView.generator.deploymentName }}/log
          livenessProbe:
            initialDelaySeconds: {{ int .Values.rawTraceView.generator.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ int .Values.rawTraceView.generator.livenessProbe.periodSeconds }}
            tcpSocket:
              port: admin-port
          readinessProbe:
            initialDelaySeconds: {{ int .Values.rawTraceView.generator.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ int .Values.rawTraceView.generator.readinessProbe.periodSeconds }}
            httpGet:
              path: /health
              port: {{ .Values.containerAdminPort }}
          resources:
            {{- toYaml .Values.rawTraceView.generator.resources | nindent 12 }}
{{- end }}