viewGeneratorGroups:
  - name: all-views-generator
    generator:
      resources:
        limits:
          cpu: 1.0
          memory: 1512Mi
        requests:
          cpu: 0.2
          memory: 320Mi
    viewGeneratorServiceConfig:
      name: all-views-generator-config
      viewgenerators:
        - view-gen-backend-entity
        - view-gen-raw-service
        - view-gen-raw-traces
        - view-gen-service-call
        - view-gen-span-event
      kafka:
        streams:
          config:
            metricsRecordingLevel: INFO
            numStreamThreads: 2
            bootstrapServers: "bootstrap:9092"
            schemaRegistryUrl: "http://schema-registry-service:8081"
