apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    release: {{ .Release.Name }}
  {{- with .Values.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- toYaml .Values.deploymentSelectorMatchLabels | nindent 6 }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: log4j-config
          configMap:
            name: {{ .Values.logConfig.name }}
    {{- with .Values.nodeLabels }}
      nodeSelector:
        {{- toYaml . | nindent 8}}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: health-port
              containerPort: {{ .Values.containerHealthProbePort }}
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: "{{ .Chart.Name }}"
            - name: CLUSTER_NAME
              value: "staging"
            - name: BOOTSTRAP_CONFIG_URI
              value: "file:///app/resources/configs"
            - name: LOG4J_CONFIGURATION_FILE
              value: "/var/{{ .Chart.Name }}/log/log4j2.properties"
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.javaOpts | quote }}
          volumeMounts:
            - name: log4j-config
              mountPath: /var/{{ .Chart.Name }}/log
          livenessProbe:
            initialDelaySeconds: {{ int .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ int .Values.livenessProbe.periodSeconds }}
            tcpSocket:
              port: health-port
          readinessProbe:
            initialDelaySeconds: {{ int .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ int .Values.readinessProbe.periodSeconds }}
            httpGet:
              path: /health
              port: {{ .Values.containerHealthProbePort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
