{{- if .Values.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-jmx-config
  labels:
    release: {{ .Release.Name }}
  {{- with .Values.deploymentLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  prometheus-raw-spans-grouper.yaml: |-
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.jmx.port }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
  {{- end }}
