apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    release: {{ .Release.Name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.containerAdminPort | quote }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.containerAdminPort }}
      targetPort: admin-port
      protocol: TCP
      name: admin-port
  selector:
    {{- toYaml .Values.serviceSelectorLabels | nindent 4 }}
