apiVersion: v2
name: hypertrace-trace-enricher
description: A Helm chart for Hypertrace Trace Enricher

type: application

version: 0.1.0

dependencies:
  - name: kafka-topic-creator
    repository: "https://storage.googleapis.com/hypertrace-helm-charts"
    version: 0.1.2
    condition: kafka-topic-creator.enabled
