{{ $global := . }}
{{- range $k, $val := .Values.viewGenIndividualConfigs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $k }}-config
  labels:
    release: {{ $global.Release.Name }}
data:
  application.conf: |-
    input.topics = {{ $val.inputTopics | toJson }}
    output.topic = {{ $val.outputTopic }}
{{- end }}