on:
  issue_comment:
    types: [created]
name: release
jobs:
  release:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/release')
    runs-on: [self-hosted]
    steps:
      - name: cleanup #https://github.com/actions/checkout/issues/211
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        with:
          repo_token: ${{ github.token }}

      - uses: actions/checkout@v2
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

#      - name: Login to Harbor
#        uses: docker/login-action@v1
#        with:
#          registry: c.rzp.io
#          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
#          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
#
      - name: git token
        env: # Or as an environment variable
          git_user: ${{ secrets.GIT_USER }}
          GIT_TOKEN: ${{ github.token }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        uses: ./.github/actions/release